# Site settings
title: Riky Lutfi Hamzah
email: rlh_258@yahoo.co.id
description: > # this means to ignore newlines until "baseurl:"
  This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rikylutfihamzah.com" # the base hostname & protocol for your site
twitter_username: rilutham
github_username:  rilutham

# Build settings
markdown: kramdown

permalink: /blog/:categories/:title