# Site Wide configuration

title: Riky Lutfi Hamzah
email: rilutham@gmail.com
locale: en_US
url: "http://rikylutfihamzah.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Site owner

owner:
  name: '@rilutham'
  avatar: riky-lutfi-hamzah-ava.jpg
  bio: "Convey to the people even if it were a single sentence. (Sahih al-Bukhari 3461)"
  email: 
  disqus-shortname: 
  twitter: rilutham
  facebook: #username
  google:
    plus: #username
    analytics: UA-34568567-2
    verify: Ov5JQc5xEZnaZdgwkduE-qUF8SRRQMh46u2KTQgFico
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: rilutham
  stackoverflow: http://stackoverflow.com/users/3474833/rilutham
  linkedin: rikylutfihamzah
  instagram: #username
  lastfm: rilutham
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
